import numpy as np
from zobrazeni import noise
from zobrazeni import show
from hopfield import Hopfield

vzor1 = np.genfromtxt('vzory\\a.csv', delimiter=';')
vzor2 = np.genfromtxt('vzory\\b.csv', delimiter=';')
vzor3 = np.genfromtxt('vzory\\c.csv', delimiter=';')
vzor4 = np.genfromtxt('vzory\\d.csv', delimiter=';')
vzor5 = np.genfromtxt('vzory\\e.csv', delimiter=';')
vzor6 = np.genfromtxt('vzory\\f.csv', delimiter=';')
vzor7 = np.genfromtxt('vzory\\g.csv', delimiter=';')
vzor8 = np.genfromtxt('vzory\\h.csv', delimiter=';')

hop = Hopfield(120)
hop.train_iter(vzor1.flatten())
hop.train_iter(vzor2.flatten())
hop.train_iter(vzor3.flatten())
hop.train_iter(vzor4.flatten())
hop.train_iter(vzor5.flatten())
hop.train_iter(vzor6.flatten())
hop.train_iter(vzor7.flatten())
hop.train_iter(vzor8.flatten())

show(vzor5)
y_noise = noise(vzor5, 1)
show(y_noise)
y_noise = hop.equip_iter(y_noise.flatten())
y_noise = np.reshape(y_noise, (12, 10))
show(y_noise)
y_noise = hop.equip_iter(y_noise.flatten())
y_noise = np.reshape(y_noise, (12, 10))
show(y_noise)
y_noise = hop.equip_iter(y_noise.flatten())
y_noise = np.reshape(y_noise, (12, 10))
show(y_noise)
y_noise = hop.equip_iter(y_noise.flatten())
y_noise = np.reshape(y_noise, (12, 10))
show(y_noise)
y_noise = hop.equip_iter(y_noise.flatten())
y_noise = np.reshape(y_noise, (12, 10))
show(y_noise)
y_noise = hop.equip_iter(y_noise.flatten())
y_noise = np.reshape(y_noise, (12, 10))
show(y_noise)
y_noise = hop.equip_iter(y_noise.flatten())
y_noise = np.reshape(y_noise, (12, 10))
show(y_noise)